const ORDERS_SHEET='Orders';
const SHOP_ORDERS_SHEET='ShopOrders';
const SETTINGS_SHEET='Settings';
const OPERATIONS_SHEET='Operations';
const SENT_SHEET='VendorSentBatches';
const RECEIPTS_SHEET='VendorReceipts';
const ADMIN_KEY=PropertiesService.getScriptProperties().getProperty('ADMIN_KEY')||''; // 僅從 Apps Script 指令碼屬性讀取，不寫入原始碼

function setup(){
  const cache=CacheService.getScriptCache();if(cache.get('schema-ready-v3'))return;
  const ss=SpreadsheetApp.getActiveSpreadsheet();
  ensureOrderSheet_(ss,ORDERS_SHEET,['月份','設計師','廠商','商品名稱','數量','更新時間','訂單鍵','規格','單價','金額','商品ID']);
  ensureOrderSheet_(ss,SHOP_ORDERS_SHEET,['月份','下單人','廠商','商品名稱','數量','更新時間','訂單鍵','規格','單價','金額','商品ID']);
  ensureSheet_(ss,SETTINGS_SHEET,['鍵','值']);ensureSheet_(ss,OPERATIONS_SHEET,['requestId','status','message','完成時間']);ensureSheet_(ss,SENT_SHEET,['月份','廠商','批次ID','品項JSON','送出時間']);ensureSheet_(ss,RECEIPTS_SHEET,['批次ID','實收JSON','點貨時間']);
  const settings=ss.getSheetByName(SETTINGS_SHEET),v=settings.getDataRange().getValues();if(!v.some(r=>r[0]==='lockMode'))settings.appendRow(['lockMode','auto']);
  cache.put('schema-ready-v3','1',21600);
}
function doGet(e){try{const p=(e&&e.parameter)||{},a=String(p.action||'bootstrap');let r;if(a==='operation')r=getOperation_(p.requestId);else{setup();if(a==='bootstrap')r=getBootstrap_();else if(a==='designerOrder')r=getDesignerOrderWithSent_(p);else if(a==='shopOrder'){requireAdmin_(p.adminKey);r=getOrder_(SHOP_ORDERS_SHEET,p,true)}else if(a==='summary')r=getSummary_(p);else r={ok:false,message:'未知 action'}}return output_(r,p.callback)}catch(err){return output_({ok:false,message:err.message||String(err)},e&&e.parameter&&e.parameter.callback)}}
function doPost(e){const p=(e&&e.parameter)||{},id=String(p.requestId||Utilities.getUuid());try{setup();const a=String(p.op||p.action||'saveOrder');let r;if(a==='saveOrder')r=saveOrder_(ORDERS_SHEET,p,false);else if(a==='saveShopOrder'){requireAdmin_(p.adminKey);r=saveOrder_(SHOP_ORDERS_SHEET,p,true)}else if(a==='deleteOwnOrder')r=deleteOwnOrder_(p);else if(a==='deleteOrder')r=deleteAdminOrder_(p);else if(a==='deleteShopOrder')r=deleteShopOrder_(p);else if(a==='setLock')r=setLock_(p);else if(a==='markVendorSent'){requireAdmin_(p.adminKey);r=saveSentBatch_(p,id)}else if(a==='updateSentBatch'){requireAdmin_(p.adminKey);r=updateSentBatch_(p)}else if(a==='deleteSentBatch'){requireAdmin_(p.adminKey);r=deleteSentBatch_(p)}else if(a==='saveReceipt'){requireAdmin_(p.adminKey);r=saveReceipt_(p)}else throw new Error('未知 action');recordOperation_(id,'success',r.message||'完成');return ContentService.createTextOutput(JSON.stringify({ok:true,requestId:id}))}catch(err){recordOperation_(id,'error',err.message||String(err));return ContentService.createTextOutput(JSON.stringify({ok:false,requestId:id,message:err.message||String(err)}))}}
function saveOrder_(sheetName,p,isShop){const person=isShop?'店用':clean_(p.designer);if(!person)throw new Error('缺少設計師姓名');if(!isShop&&isLocked_()&&String(p.adminKey||'')!==ADMIN_KEY)throw new Error('本月叫貨已截止');const month=normalizeMonth_(p.month);let items;try{items=JSON.parse(String(p.items||'[]'))}catch(_){throw new Error('商品資料格式錯誤')}if(!Array.isArray(items)||!items.length)throw new Error('貨單沒有商品');validateSentFloor_(month,isShop?'W.D 店用':person,items);const key=makeKey_(month,person,isShop),lock=LockService.getScriptLock();lock.waitLock(30000);try{const s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(sheetName);deleteRowsMatching_(s,row=>String(row[6]||'')===key||(normalizeStoredMonth_(row[0])===month&&keyText_(row[1])===keyText_(person)));const now=Utilities.formatDate(new Date(),'Asia/Taipei','yyyy/MM/dd HH:mm:ss');const rows=items.filter(x=>Number(x.qty)>0).map(x=>{const qty=Number(x.qty)||0,price=Number(x.price)||0;return[month,person,String(x.vendor||''),String(x.name||''),qty,now,key,String(x.spec||''),price,qty*price,String(x.productId||'')]});if(!rows.length)throw new Error('貨單沒有有效數量');s.getRange(s.getLastRow()+1,1,rows.length,11).setValues(rows);s.getRange(s.getLastRow()-rows.length+1,1,rows.length,1).setNumberFormat('@');SpreadsheetApp.flush()}finally{lock.releaseLock()}return{message:(isShop?'店用':person)+' '+month+' 貨單已儲存'}}
function sentItemKey_(x){const id=clean_(x.productId);return id?'id:'+id:'item:'+keyText_(x.vendor)+'|'+keyText_(x.name)+'|'+keyText_(x.spec)}
function validateSentFloor_(month,person,items){const sent={},current={};readSentBatches_().filter(b=>b.month===month).forEach(b=>(b.items||[]).filter(x=>keyText_(x.owner)===keyText_(person)).forEach(x=>{const k=sentItemKey_(x);sent[k]=(sent[k]||0)+(Number(x.qty)||0)}));items.forEach(x=>{const k=sentItemKey_(x);current[k]=(current[k]||0)+(Number(x.qty)||0)});for(const k in sent)if((current[k]||0)<sent[k])throw new Error('已送給廠商的品項不能減少或刪除，只能追加數量')}
function getOrder_(sheetName,p,isShop){const person=isShop?'店用':clean_(p.designer),month=normalizeMonth_(p.month);if(!person)return{ok:true,month,items:[]};const s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(sheetName),key=makeKey_(month,person,isShop),items=[];const v=s.getDataRange().getValues(),d=s.getDataRange().getDisplayValues();for(let i=1;i<v.length;i++){const r=v[i],shown=d[i],matched=String(r[6]||shown[6]||'')===key||(normalizeStoredMonth_(r[0]||shown[0])===month&&keyText_(r[1]||shown[1])===keyText_(person));if(matched)items.push({vendor:r[2]||shown[2],name:r[3]||shown[3],qty:Number(r[4]||shown[4])||0,updatedAt:r[5]||shown[5],spec:r[7]||shown[7]||'',price:Number(r[8]||shown[8])||0,amount:Number(r[9]||shown[9])||0,productId:r[10]||shown[10]||''})}return{ok:true,month,items,locked:isLocked_()}}
function getDesignerOrderWithSent_(p){const r=getOrder_(ORDERS_SHEET,p,false),owner=clean_(p.designer);r.sentBatches=readSentBatches_().filter(b=>b.month===r.month).map(b=>({vendor:b.vendor,batchId:b.batchId,sentAt:b.sentAt,items:b.items.filter(x=>keyText_(x.owner)===keyText_(owner))})).filter(b=>b.items.length);return r}
function deleteOwnOrder_(p){if(isLocked_())throw new Error('本月已截止，請由店長刪除');return deleteByPerson_(ORDERS_SHEET,normalizeMonth_(p.month),clean_(p.designer),false)}
function deleteAdminOrder_(p){requireAdmin_(p.adminKey);return deleteByPerson_(ORDERS_SHEET,normalizeMonth_(p.month),clean_(p.designer),false)}
function deleteShopOrder_(p){requireAdmin_(p.adminKey);return deleteByPerson_(SHOP_ORDERS_SHEET,normalizeMonth_(p.month),'店用',true)}
function deleteByPerson_(sheetName,month,person,isShop){if(!person)throw new Error('缺少名稱');const s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(sheetName),key=makeKey_(month,person,isShop);deleteRowsMatching_(s,row=>String(row[6]||'')===key||(normalizeStoredMonth_(row[0])===month&&keyText_(row[1])===keyText_(person)));SpreadsheetApp.flush();return{message:person+' 的 '+month+' 貨單已刪除'}}
function getSummary_(p){requireAdmin_(p.adminKey);const month=normalizeMonth_(p.month),ss=SpreadsheetApp.getActiveSpreadsheet(),designerRows=rowsForMonth_(ss.getSheetByName(ORDERS_SHEET),month),shopRows=rowsForMonth_(ss.getSheetByName(SHOP_ORDERS_SHEET),month),designers={},vendors={};let designerTotal=0,shopTotal=0;
  designerRows.forEach(r=>{const person=String(r[1]),x=rowItem_(r);designerTotal+=x.amount;if(!designers[person])designers[person]={updatedAt:String(r[5]||''),amount:0,items:[]};designers[person].items.push(x);designers[person].amount+=x.amount;if(String(r[5]||'')>designers[person].updatedAt)designers[person].updatedAt=String(r[5]||'');addVendor_(vendors,x)});
  shopRows.forEach(r=>{const x=rowItem_(r);shopTotal+=x.amount;addVendor_(vendors,x)});
  const receiptMap=readReceiptMap_(),sentBatches=readSentBatches_().filter(b=>b.month===month).map(b=>({...b,receipt:receiptMap[b.batchId]||null}));return{ok:true,month,locked:isLocked_(),lockMode:getSetting_('lockMode','auto'),designers,shopItems:shopRows.map(rowItem_),orders:Object.entries(designers).map(([owner,o])=>({type:'designer',owner,items:o.items})).concat([{type:'shop',owner:'W.D 店用',items:shopRows.map(rowItem_)}]),sentBatches,vendors,totals:{designer:designerTotal,shop:shopTotal,grand:designerTotal+shopTotal}}}
function saveSentBatch_(p,id){const month=normalizeMonth_(p.month),vendor=clean_(p.designer);let items;try{items=JSON.parse(String(p.items||'[]'))}catch(_){throw new Error('送出紀錄格式錯誤')}items=(Array.isArray(items)?items:[]).map(x=>({owner:clean_(x.owner),productId:clean_(x.productId),vendor:clean_(x.vendor||vendor),name:clean_(x.name),spec:clean_(x.spec),qty:Math.max(0,Number(x.qty)||0),price:Math.max(0,Number(x.price)||0)})).filter(x=>x.owner&&x.vendor&&x.name&&x.qty>0);if(!vendor||!items.length)throw new Error('沒有待送出的追加品項');const s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SENT_SHEET),v=s.getDataRange().getValues();if(v.slice(1).some(r=>String(r[2])===String(id)))return{message:'送出紀錄已存在'};s.appendRow([month,vendor,id,JSON.stringify(items),Utilities.formatDate(new Date(),'Asia/Taipei','yyyy/MM/dd HH:mm:ss')]);return{message:vendor+' 送出紀錄已儲存'}}
function updateSentBatch_(p){const batchId=clean_(p.batchId);let items;try{items=JSON.parse(String(p.items||'[]'))}catch(_){throw new Error('批次資料格式錯誤')}items=(Array.isArray(items)?items:[]).map(x=>({owner:clean_(x.owner),productId:clean_(x.productId),vendor:clean_(x.vendor),name:clean_(x.name),spec:clean_(x.spec),qty:Math.max(0,Number(x.qty)||0),price:Math.max(0,Number(x.price)||0)})).filter(x=>x.owner&&x.vendor&&x.name&&x.qty>0);if(!batchId)throw new Error('缺少批次編號');if(!items.length)throw new Error('批次至少要保留一個品項，若要全部移除請使用刪除批次');const s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SENT_SHEET),v=s.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][2])===batchId){s.getRange(i+1,4).setValue(JSON.stringify(items));return{message:'批次紀錄已更新'}}throw new Error('找不到此批次紀錄')}
function deleteSentBatch_(p){const batchId=clean_(p.batchId);if(!batchId)throw new Error('缺少批次編號');const s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SENT_SHEET),v=s.getDataRange().getValues();for(let i=v.length-1;i>=1;i--)if(String(v[i][2])===batchId){s.deleteRow(i+1);const rs=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(RECEIPTS_SHEET),rv=rs.getDataRange().getValues();for(let j=rv.length-1;j>=1;j--)if(String(rv[j][0])===batchId)rs.deleteRow(j+1);return{message:'誤觸批次與點貨紀錄已刪除'}}throw new Error('找不到此批次紀錄')}
function receiptItemKey_(x){return [clean_(x.owner),clean_(x.productId),clean_(x.vendor),clean_(x.name),clean_(x.spec)].join('|')}
function saveReceipt_(p){const batchId=clean_(p.batchId);if(!batchId)throw new Error('缺少批次編號');let received;try{received=JSON.parse(String(p.items||'[]'))}catch(_){throw new Error('點貨資料格式錯誤')}if(!Array.isArray(received))throw new Error('點貨資料格式錯誤');const batch=readSentBatches_().find(b=>b.batchId===batchId);if(!batch)throw new Error('找不到此叫貨批次');const allowed={};batch.items.forEach(x=>allowed[receiptItemKey_(x)]=true);received=received.map(x=>({key:clean_(x.key),receivedQty:Math.max(0,Math.floor(Number(x.receivedQty)||0))})).filter(x=>allowed[x.key]);if(received.length!==batch.items.length)throw new Error('點貨品項不完整，請重新整理後再試');const s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(RECEIPTS_SHEET),v=s.getDataRange().getValues(),now=Utilities.formatDate(new Date(),'Asia/Taipei','yyyy/MM/dd HH:mm:ss'),json=JSON.stringify(received);for(let i=1;i<v.length;i++)if(String(v[i][0])===batchId){s.getRange(i+1,2,1,2).setValues([[json,now]]);return{message:'點貨紀錄已更新'}}s.appendRow([batchId,json,now]);return{message:'點貨紀錄已儲存'}}
function readReceiptMap_(){const s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(RECEIPTS_SHEET),out={};if(!s)return out;s.getDataRange().getValues().slice(1).forEach(r=>{if(!r[0])return;let items=[];try{items=JSON.parse(String(r[1]||'[]'))}catch(_){}out[String(r[0])]={items,checkedAt:String(r[2]||'')}});return out}
function readSentBatches_(){return SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SENT_SHEET).getDataRange().getValues().slice(1).filter(r=>r[0]).map(r=>({month:normalizeStoredMonth_(r[0]),vendor:String(r[1]||''),batchId:String(r[2]||''),items:(()=>{try{return JSON.parse(String(r[3]||'[]'))}catch(_){return[]}})(),sentAt:String(r[4]||'')}))}
function rowItem_(r){const qty=Number(r[4])||0,price=Number(r[8])||0;return{vendor:String(r[2]||''),name:String(r[3]||''),qty,spec:String(r[7]||''),price,amount:Number(r[9])||qty*price,productId:String(r[10]||'')}}
function addVendor_(vendors,x){if(!vendors[x.vendor])vendors[x.vendor]={amount:0,items:{}};const k=x.name+'||'+x.spec+'||'+x.price;if(!vendors[x.vendor].items[k])vendors[x.vendor].items[k]={name:x.name,spec:x.spec,price:x.price,qty:0,amount:0};vendors[x.vendor].items[k].qty+=x.qty;vendors[x.vendor].items[k].amount+=x.amount;vendors[x.vendor].amount+=x.amount}
function rowsForMonth_(s,month){return s.getDataRange().getValues().slice(1).filter(r=>normalizeStoredMonth_(r[0])===month)}
function setLock_(p){requireAdmin_(p.adminKey);const mode=String(p.mode||'auto');if(!['auto','locked','open'].includes(mode))throw new Error('鎖定模式錯誤');setSetting_('lockMode',mode);return{message:'鎖定模式已更新'}}
function getBootstrap_(){return{ok:true,month:currentMonth_(),locked:isLocked_(),lockMode:getSetting_('lockMode','auto'),cutoffText:'每月20日23:59截止'}}
function getOperation_(id){const v=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(OPERATIONS_SHEET).getDataRange().getValues();for(let i=v.length-1;i>=1;i--)if(String(v[i][0])===String(id||''))return{ok:true,found:true,status:v[i][1],message:v[i][2],finishedAt:v[i][3]};return{ok:true,found:false}}
function recordOperation_(id,status,message){SpreadsheetApp.getActiveSpreadsheet().getSheetByName(OPERATIONS_SHEET).appendRow([id,status,message,Utilities.formatDate(new Date(),'Asia/Taipei','yyyy/MM/dd HH:mm:ss')])}
function output_(data,cb){const json=JSON.stringify(data);return cb?ContentService.createTextOutput(cb+'('+json+')').setMimeType(ContentService.MimeType.JAVASCRIPT):ContentService.createTextOutput(json).setMimeType(ContentService.MimeType.JSON)}
function ensureOrderSheet_(ss,name,headers){let s=ss.getSheetByName(name),changed=false;if(!s){s=ss.insertSheet(name);changed=true}if(s.getLastRow()===0){s.appendRow(headers);changed=true}else if(s.getLastColumn()<headers.length){s.getRange(1,1,1,headers.length).setValues([headers]);changed=true}if(changed)s.getRange(1,1,Math.max(2,s.getLastRow()),1).setNumberFormat('@');return s}
function ensureSheet_(ss,name,headers){let s=ss.getSheetByName(name);if(!s)s=ss.insertSheet(name);if(s.getLastRow()===0)s.appendRow(headers);return s}
function deleteRowsMatching_(s,pred){const v=s.getDataRange().getValues();for(let i=v.length-1;i>=1;i--)if(pred(v[i]))s.deleteRow(i+1)}
function clean_(v){return String(v==null?'':v).replace(/\s+/g,' ').trim()}function keyText_(v){return clean_(v).toLocaleLowerCase()}
function makeKey_(month,person,isShop){return month+'::'+(isShop?'shop':keyText_(person))}
function normalizeStoredMonth_(v){if(Object.prototype.toString.call(v)==='[object Date]'&&!isNaN(v))return Utilities.formatDate(v,'Asia/Taipei','yyyy-MM');const s=String(v==null?'':v).trim(),m=s.match(/(20\d{2})\D{0,3}(\d{1,2})/);return m?m[1]+'-'+String(Number(m[2])).padStart(2,'0'):s}
function currentMonth_(){return Utilities.formatDate(new Date(),'Asia/Taipei','yyyy-MM')}function normalizeMonth_(v){const s=String(v||currentMonth_());return /^\d{4}-\d{2}$/.test(s)?s:currentMonth_()}
function isLocked_(){const m=getSetting_('lockMode','auto');if(m==='open')return false;if(m==='locked')return true;return Number(Utilities.formatDate(new Date(),'Asia/Taipei','d'))>20}
function requireAdmin_(k){if(String(k||'')!==ADMIN_KEY)throw new Error('店長密碼錯誤')}
function getSetting_(key,fallback){const v=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SETTINGS_SHEET).getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===key)return String(v[i][1]);return fallback}
function setSetting_(key,value){const s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SETTINGS_SHEET),v=s.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===key){s.getRange(i+1,2).setValue(value);return}s.appendRow([key,value])}
